#!/bin/bash
# chkconfig: 345 90 10 
# description: Control oracle database process
#
# File: /etc/init.d/oracle
# Purpose: Start and stop the Oracle database services
# Author: bthompso (Conundrum)
# Date: 3/11/2014
#
# Absolutely no warranty, use at your own risk
# Please include this header in any copy or reuse of the script you make
#
# Version 0.01
#
# Usage:
#	1: Create file at /etc/init.d/oracle
#	2: chmod 750 /etc/init.d/oracle
#	3: chkconfig --add oracle
#
#------------------------------------
#
# The following values must be changed for your environment
#

ORACLE_HOME=ORACLE_HOME
ORACLE_USER=oracle



# The following values should not need to be modified

SUBSYS=$(basename $0)
LOCKFILE='/var/lock/subsys/'$SUBSYS

#-----------------------------------------------


# source init.d functions
#----------------------------
. /etc/rc.d/init.d/functions

# source environment variables
. /home/oracle/OBITEST.env
#----------------------------


case "$1" in
'start')
   if [ -f $LOCKFILE ]; then
      echo $0 already running.
      exit 1
   fi
   echo -n $"Starting Oracle Database:"
#   su $ORACLE_USER -c "$ORACLE_HOME/bin/lsnrctl start"
   su $ORACLE_USER -c "$ORACLE_HOME/bin/dbstart $ORACLE_HOME"
#   su - $ORACLE_USER -c "$ORACLE_HOME/bin/emctl start dbconsole"
   touch $LOCKFILE
   ;;
'stop')
   if [ ! -f $LOCKFILE ]; then
      echo $0 already stopping.
      exit 1
   fi
   echo -n $"Stopping Oracle Database:"
#   su $ORACLE_USER -c "$ORACLE_HOME/bin/lsnrctl stop"
   su $ORACLE_USER -c "$ORACLE_HOME/bin/dbshut $ORACLE_HOME"
#   su - $ORACLE_USER -c "$ORACLE_HOME/bin/emctl stop dbconsole"
   rm -f $LOCKFILE
   ;;
'restart')
   $0 stop
   $0 start
   ;;
'status')
   echo -n ' Oracle Status is '
   if [ -f $LOCKFILE ]; then
      echo_success
      else
      echo_not_running
   fi
   ;;
*)
   echo "Usage: $0 [start|stop|status]"
   exit 1
esac

exit 0






